### PR TITLE
Move support to Ruby 2.3.0

### PR DESCRIPTION
**Pull request by adamgeorgeson**

### CODE REVIEW

**Review by chrisbarber86 — APPROVED** [review]
:+1: Should we mention something in the ReadME?

**Comment by cpetschnig** [comment]
Is this really necessary? People are sometimes slow to upgrade. I would rather recommend extending support to 1.9.

**Comment by chrisbarber86** [comment]
@cpetschnig Good point, maybe we can still support the other versions and keep them as part of the travis options. cc @adamgeorgeson

**Comment by adamgeorgeson** [comment]
@cpetschnig @chrisbarber86 Sure. Travis is failing `2.0.0` and `2.1.6` builds because it's trying to use activesupport from rails 5, which is `v2.2.2` and above. We can solve this PR a different way by updating gemspec to resolve this.

**Pull request closed without merging**
